### ISSUE TITLE
Summon

### ISSUE THREAD

**Issue by TouchTitans** [hjespers/teslams#100]
Adding summon. Keep running into this error:
I keep getting "too_far_from_vehicle error". 

Add the following to Teslams.js
// summon
function summon( vid, cb) {
  console.log("summon");
    request( {
        method: 'POST',
        url: portal + '/vehicles/' + vid + '/command/autopark_request',
        gzip: true,
        headers: http_header,
        lat: yourlat,
        lon: yourlong,
        action: 'start_reverse'
        //homelink_nearby: true
    }, function (error, response, body) {
        if ((!!error) || (response.statusCode !== 200)) return report(error, response, body, cb);
        try {
            var data = JSON.parse(body);
            if (typeof cb == 'function') return cb( data.response );
            else return true;

        } catch (err) {
            return report2('autopark_request', body, cb);
        }
    });
}
exports.summon = summon;

**Comment by hjespers** [comment]
If someone can show be working code or a curl command then I can help debit this but since my car is a pre-AP car I have no direct way to test summon.

**Comment by tekkkon** [comment]
any luck with this feature?

**Comment by TouchTitans** [comment]
i think homelink is the only way for now.

**Comment by hjespers** [comment]
There must be a way to make it work because the Remote S app supports summon and so does the mobile app from Tesla.

**Comment by jsgoecke** [comment]
This works:

https://github.com/jsgoecke/tesla/blob/summon/commands.go#L28
