### ISSUE TITLE
add stand alone login() method to teslams.js which fetches token

### ISSUE THREAD

**Issue by hjespers** [hjespers/teslams#106]
Some people would prefer to manage their own login tokens rather than request a new one each time their apps start. 

I should add into teslams.js an explicit login() method that sets the global variable for the token and does nothing else. This is done now, only when you call vehicles() or all()

Modify teslacmd.js to have an option to print out the token.

Modify config.js to check the ~/.teslams.json file for a token that the user has saved instead of their username and password. 

Modify vehicles()  and all() to check if the global token variable is already set and if so, skip the login part of the code. May enhance this later to check for expired tokens.

**Comment by bjm88** [comment]
Hi - sorry I am a little confused by this statement.  I am calling the https://owner-api.teslamotors.com/oauth/token service directly and getting and storing the response encrypted internally in my app to have access to the access and refresh tokens..
{
  "access_token": "abc123",
  "token_type": "bearer",
  "expires_in": 7776000,
  "refresh_token": "456zyw",
  "created_at": 1483413170
}
I would like to use this library to work with the rest of the api, but want to pass in an access_token initially or on each call is fine, and NOT The username / password.  Is this possible and being covered with this issue or should I open a separate issue to track it?

**Comment by mseminatore** [comment]
I interpret Hans' comments to mean what you said, that you could provide your own token.  Though it is not entirely clear whether you can provide the token with each call or whether you must set the token as global state.

There are other similar wrapper libraries for example (full disclosure: this one is my own) [TeslaJS](https://www.npmjs.com/package/teslajs) that are stateless and offer the ability to pass the token with each call.

**Comment by bjm88** [comment]
Thank you mseminatore  I will check out your library, looks nice.

**Comment by hjespers** [comment]
The auth token is stored once in the variable "http_header". You can see an example of how the http_header is set here https://github.com/hjespers/teslams/blob/master/teslams.js#L54

The only functions in this library that use login and password are all(), vehicles(), and get_vid(). If you already have a token and know your vehicle_id then you can skip calling these functions, set up http_header yourself and all the other functions should work.

This enhancement request was a note to myself to add explicit functions to setToken() and getToken() that would make it easier for developing.

**Comment by hjespers** [comment]
I added in a set_token() method and expanded the teslacmd example to show how to use it.
Just call set_token( id, token) where id is the id_s string of the car and token is a valid authentication bearer token. This will then cause all subsequent calls to the API to use the token specified. I have not published the change to npm yet so pull from github and let me know if it works for you.

**Comment by hjespers** [comment]
Not sure what I was thinking but "id" is not required for set_token. Just call teslams.set_token( token )

**Comment by hjespers** [comment]
finished implementation of tokens and published to npm as teslams version 1.2.2
all the examples should now take --token as an argument or you can store a token in your ~/.teslams/config.json in place of username and password using the following format:

{
    "token": "abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123"
}

**Comment by bjm88** [comment]
Thanks hjespers!  exactly what was required :)

**Comment by bjm88** [comment]
Hi hjespers, just getting back to this, and I actually found using set token isn't working.. here is my usage...tried setting before and on call.....

teslams.set_token( process.env.TSLA_AUTH_TOKEN )

teslams.get_vid( { token: process.env.TSLA_AUTH_TOKEN }, function ( id ) {
	console.log("Got VID " + id)
	//teslams.get_vehicle_state( id , function ( state) {
	//	console.log( util.inspect( state ) );
	//});
	teslams.get_charge_state( id , function ( state) {
		//console.log( util.inspect( state ) );
		console.log("Your Tesla is " + state["charging_state"] + " and charged for a range of " + state["battery_range"] + " miles" );
	});
});

**Comment by hjespers** [comment]
If you want to see a working example, the application examples/teslacmd.js uses set_token() and can set it either from a command line argument called --token or via the config.js file in your ~/.teslams directory. The code for the second method uses config.js which could be extended to read from an environment variable as in your example. Once you call set_token you can then read it current value from the global variable teslams.token. The teslacmd.js app also has a --print_token flag to print out this global variable on the command line.
