### ISSUE TITLE
Any idea how to call teslams from an AWS Lambda function?

### ISSUE THREAD

**Issue by kennethchapman99** [hjespers/teslams#109]
AWS Lambda doesn't support 'Request' 3rd party module -- so I am kinda stuck.

Have a stand-alone Lambda function I've writing using AWS Lambda console and can't figure out how to call the Tesla API from it...

**Comment by kennethchapman99** [comment]
I tried installing teslams via NPM INSTALL after cloning the repository...
Zipping that up with my function.js file gives me an error:

{
  "errorMessage": "Cannot find module 'index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

**Comment by hjespers** [comment]
Did you follow this approach? https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

**Comment by kennethchapman99** [comment]
yeah - was managing the handler function names incorrectly.  Thanks for the link, one more Noob hurdle overcome :)

**Comment by hjespers** [comment]
I haven't documented it yet but streaming.js can publish streaming telemetry from the car to AWS IOT and I have successfully routed that traffic to both AWS Lambda for realtime processing and AWS DynamoDB for storage.

**Comment by array-addu** [comment]
@hjespers How can i use streaming API with Lambda as Lambda functions times out after 5 mins which also stops streaming ?

**Comment by hjespers** [comment]
You can’t run the streaming.js app itself inside AWS Lambda because Lambda doesn’t run continuously. What you have to do is run streaming.js on a local host or in AWS EC2 and have it publish to AWS IOT (this uses mqtt). Then you can route the AWS IOT events into Lambda and do some processing there. You can also route the messages to DynamoDB or and S3 bucket or whatever you want in a pure AWS world.

**Comment by array-addu** [comment]
> You can’t run the streaming.js app itself inside AWS Lambda
Yes, i am using streaming API with these parameters
`[ 'speed','odometer','soc','elevation','est_heading','est_lat','est_lng','power','shift_state','range','est_range','heading'];`
and getting the values every 2 sec but dont know what is the best way to deal with the data.

> What you have to do is run streaming.js on a local host or in AWS EC2 and have it publish to AWS IOT (this uses mqtt).
Is it not possible without using EC2, with Lambda only. Actually i have to monitor the values when any vehicle state changes.
