### ISSUE TITLE
Use inside AWS Lambda

### ISSUE THREAD

**Issue by bjm88** [hjespers/teslams#114]
Hi - wondering if anyone has tried using inside of AWS Lambda.  I had it working about 2 months ago, and updated library to get the support for passing a token instead of user / pwd, and now my Lambda call is timing out.   I tried increasing memory to 256 MB and also timeout to 30 seconds, didn't help.

Its very weird b/c I can use the http lib "request" that teslams uses internally and make a call to google fine, but if I try to call through a teslams.get_vehicle or other call it hangs.  Also tried using request to call https://owner-api.teslamotors.com/api/1 directly and that hung as well.  

Some conflict or filter AWS has or Tesla blocking calls from AWS Lambda somehow?  Would love to know if anyone else has any luck.  Thanks.

**Comment by ssmughal** [comment]
I’m guessing it’s the same issue that’s been affecting multiple cloud services, as described here:  https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-96.

**Comment by hjespers** [comment]
check it now that the AWS block is supposedly no longer in effect

**Comment by array-addu** [comment]
it's now working with lambda
