### ISSUE TITLE
Supercharger availabilities API?

### ISSUE THREAD

**Issue by c2h2** [hjespers/teslams#123]
Supercharger availabilities API? Showing locations and how many are vacant?

**Comment by hjespers** [comment]
Not sure that even possible in the API. If it is can you point me to these functions?

**Comment by c2h2** [comment]
Like availability info, location info? you can view them on Telsa in-car big screen.

**Comment by hjespers** [comment]
Yes you can view and control a lot of things on the Tesla Console that are not available via the mobile app and therefore also not available via the REST API

**Comment by c2h2** [comment]
Can we intercept the packets via a proxy and find out if this is a RESTful API?

**Comment by hjespers** [comment]
Doing that is much harder than putting a man in the middle of the Tesla mobile app or decompiling the Mobile app, both of which are easy. The car has VPN software and keys stored on the MCU so hacking it involved voiding your warrenty and ripping open your dash and the MCU. I’m leaving that work to others ;-)
