### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by cbrandlehner** [hjespers/teslams#125]
When using teslacmd -u x -p y (x and y are not the credentials I really used)
I get the error message:

```
Error parsing response to oauth token request
Error: login `failed`
```
I can login on the tesla.com site so username and password are correct.

**Comment by cbrandlehner** [comment]
I found a solution that worked for me and created a pull request.
#126

**Comment by cbrandlehner** [comment]
@flexgames the usecase I was addressing was teslacmd not being able to login.
I just verified and can confirm that the fix provided works for teslacmd.
Larger picture is that I use teslams in node-red which is fixed by this too. See:
https://github.com/hjespers/node-red-contrib-teslams

**Comment by cbrandlehner** [comment]
@flexgames I was able to reproduce the problem with streaming and submitted an updated fix #126

**Comment by wtonsp** [comment]
Thanks for the fix!  Was about to look into this and someone already fixed it :)

**Comment by jaslo** [comment]
Has that pull request been merged? I am seeing that issue also.

**Comment by MichaelSinz** [comment]
I can confirm that this does solve the problem.  Please merge the change/fix to master.  It seems clean.

**Comment by flexgames** [comment]
works for me! Thanks for all your help @cbrandlehner !

**Comment by cbrandlehner** [comment]
I do not have write access to this repository. I hope @hjespers will respond soon, he did a great job in crating this repository.
If @hjespers is unavailable I am considering creating a new fork of this project.

**Comment by hjespers** [comment]
I will merge the PR

**Comment by cbrandlehner** [comment]
fixed and merged. #126

**Comment by ddaddy** [comment]
Can this fix be pushed to NPM?
