### ISSUE TITLE
npm reports incorrect license expression

### ISSUE THREAD

**Issue by cbrandlehner** [hjespers/teslams#127]
When performing "npm install":
`npm WARN teslams@1.2.2 license should be a valid SPDX license expression'

The license in package.json is defined as:
` "license": "BSD"`

Looking at the SPDX site the are several BSD licenses listed:
https://spdx.org/licenses/

The BSD license requires that the license text is distributed with the software, not the case at the moment.

**Comment by hjespers** [comment]
merges your PR to fix. Thank you
