### ISSUE TITLE
Make Visualize Multi-User Multi-Car capable

### ISSUE THREAD

**Issue by mkuendig** [hjespers/teslams#68]
Have an option that multiple users can look at their cars. Non-Geek people would like the functionality but won't set up a complete server for them. Having one server collecting multiple cars and only allowing the people to see their own data would be really cool.

**Comment by hjespers** [comment]
added in multi-car support for teslacmd.js and streaming.js in Version 1.0.3. Just specify "--vehicle 0" or "--vehicle 1" to specify which car the commend applies to. If you run two copies of streaming.js with different vehicles, make sure to give each car a unique mongodb database name as well. The visualize app can be launched as before with the database name for the car you want to view.
