### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by gutenye** [hjespers/teslams#82]
I try to use the cmd `teslacmd -a` and got

```
Teslamotors.com logon information loaded from ~/.teslams/config.json
[Error: expecting an array from Tesla Motors cloud service]
```

I pretty sure the login and password are correct. It looks like Tesla has changed  the API. .Any help would be greatly appreciated.

**Comment by hjespers** [comment]
Should be working now. This does happen some times when Tesla temporarily shuts down their authentication servers.
