### ISSUE TITLE
Getting 404 with example code

### ISSUE THREAD

**Issue by kyrios** [hjespers/teslams#83]
I'm evaluating this library and the examples work so far when I provide username and password on the commandline. But starting from example.js I don't have any success with my own 'code'

    #!/usr/bin/env node
    var teslams = require('teslams');
    var util = require('util');

    // Config
    var config = {
        creds: {
            username: 'myemail@domain.tld',
            password: 'mypassword'
        }
    };

    // Generic callback function to print the return value
    function pr( stuff ) {
        console.log( util.inspect( stuff ) );
    }

    console.log(config.creds);

    teslams.get_vid( { email: config.creds.email, password: config.creds.password }, function ( vid ) {
        if (vid == undefined) {
            console.log("Error: Undefined vehicle id");
        } else {
            teslams.get_charge_state( vid, pr );
        }
      }
    );

Results in:

    { username: 'myemail@domain.tld', password: 'mypassword' }
    [Error: 404: 404]
    [Finished in 1.7s]

Any advice?

(Password and username changed for this report of course)

**Comment by hjespers** [comment]
Your code is not setting the email parameter correctly. Change config.creds.email to config.creds.username. As it is now that is a null value, hence the 404 error.

**Comment by kyrios** [comment]
This was an error with the bugreport only. Unfortunately my original statement was false. the examples/example.js gives me a 404. Does the example (still?)work for you?

**Comment by hjespers** [comment]
example.js works for me as does the code you posted with the one change I suggested.
