### ISSUE TITLE
Error logging in while using streaming and teslacmd

### ISSUE THREAD

**Issue by marcus-no** [hjespers/teslams#86]
<user>@<hostname>:~$ streaming

Teslamotors.com logon information loaded from /home/<user>/.teslams/config.json
14 Nov 04:33:23 - timestamp,speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading
Error parsing response to oauth token request
14 Nov 04:33:24 - [Error: login failed
err: TypeError: Cannot read property 'charAt' of undefined
body: undefined]
14 Nov 04:33:24 - Info: car is in (undefined) state, calling /charge_state to reveal the tokens
14 Nov 04:33:25 - Warn: waking up with charge_state request failed.
  Waiting 30 secs and then reinitializing...

and

<user>@<hostname>:~$ teslacmd
Teslamotors.com logon information loaded from /home/<user>/.teslams/config.json
Error parsing response to oauth token request
[Error: login failed]

**Comment by hjespers** [comment]
Can you try again with the latest version 1.0.3 and see if that fixes your authentication issue?

**Comment by marcus-no** [comment]
Seems to be working now. Thanks!
