### ISSUE TITLE
Status of restla.js

### ISSUE THREAD

**Issue by ctramnitz** [hjespers/teslams#89]
I was planning to use restla.js for some integrations but then it seemed to be deprecated (removed from readme and procfile), but know I see updates to it again. Whats the status, is it supposed to work? Would you mind putting the usage options back into the readme?

**Comment by hjespers** [comment]
Yes I did pull it out for a while because it was full of bugs but now I have resurrected it again and made sure it works properly. I will put the usage options back into the readme.
