### ISSUE TITLE
Merge Restla and Visualize

### ISSUE THREAD

**Issue by ve6rah** [hjespers/teslams#91]
It seems clunky to have Restla run a web server on one port, and Visualize run on a different port, would it not make more sense to have Restla as a menu button within visualize?

**Comment by ctramnitz** [comment]
Restla is an API (proxy), Visualize a UI. They share nothing (restla requires teslamotors credentials, visualize.js needs mongodb access), so while it would be technically possible I do not see a benefit. If needed you could reverse proxy both to be available on the port / base URL.

**Comment by ve6rah** [comment]
It's about thinking about it from an end-user perspective, not from a backend resources perspective. Having restla as a tab within visualize allows for all the functionality in one place. and creates a full featured experience. The current system is far from user friendly.

**Comment by ctr49** [comment]
Huh? Which part of restla do you want to use in the browser? Its an API and its primary purpose is to encapsulate authentication from the component accessing it. If you had a web-application that accesses restla it would make sense to integrate with Visualize, but not restla itself.

**Comment by hjespers** [comment]
I did write restla to be more of a proxy and not a UI. It's a very bad UI. It would be nice to have a separate example UI that does look pretty and can control the car.

**Comment by ve6rah** [comment]
From a user experience point of view, I want another tab in visualize that allows for car control. I'm willing to help with the "make pretty" part, but I don't even know where to start with the aging or in part. As restla creates a Web server on port 8888 which seems to add the basic functionality, I would think that I could start from there and modify it to look decent, I just don't know how get both on to the same Web server.

**Comment by hjespers** [comment]
Visualize uses 'express' as the web server and restla just uses the http server built into node. It shouldn't be too hard to integrate the two together. BTW both these apps can run on any port you want them to. I think you just add --port at start time.

**Comment by hjespers** [comment]
I am working on a better stand alone GUI for controlling the car. I will leave restla as a par REST proxy (not a GUI for users) and publish and refine the GUI and merge it with Visualize once its finished
