### ISSUE TITLE
Charge status does not work

### ISSUE THREAD

**Issue by grasvezel** [hjespers/teslams#92]
Getting the charge/battery status does not work for me. It seems that the encoding is not handled correctly.

alex@b52:~/teslams$ examples/teslacmd.js -c
[Error: expecting JSON response to charge_state request]

I altered the code to display the response. This is the contents of 'body' (in teslams.js) at the time the error message is generated:

_�H@@@@@@CtT�n�0P�W�Q"0��r��W+YN��%cS?؝���[�a&�ɑ�����6�̒��vĚw�N��R��y�Qa�[�e+F\�Qz�L˚_��(*�o�Qj�ԏjF��5O�Ay�Q�V�^*.B9�ث����ODm�[�m�6�
{�!����_b�y�*c^�Tm�D���4�U;{+�5�CMNo��Y0�9�҈���w��b&��x[pL����?��WQ�R�kG�����E�'�b����=HB��VUp8���➥����I�AW�T�L�lUz����A8r��[S   �N�
�RVw���h�s��ʏ��@@@��C@q��3�D@@]

**Comment by hjespers** [comment]
Crap. This is a known bug with compressed responses that I fixed and then broke again. I think its fixed in the version I just put on github. Works for me.

**Comment by grasvezel** [comment]
Works for me too, thanks.
