### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by grasvezel** [hjespers/teslams#93]
Sorry to bug you right away with another issue.

Streaming does not work for me, I get "WARN: HTTP 401: Unauthorized - token has likely expired, reinitializing". I've saved my u/p in config.json, it works for the other scripts. 

Not sure if it has anything to do with this problem (probably not), but this script can not be executed from any directory. If I start it from ~/teslams/ it does not find config.json. The other scripts do.

**Comment by hjespers** [comment]
if you add "--debug" as an option it should print out where it's loading the config data from. It should be using the same config.js config loader routine so its off that it works for the other tools and not this one.

**Comment by grasvezel** [comment]
examplestream.js does not load the config unless I change to the directory the script is in:

alex@b52:~/teslams$ examples/examplestream.js --debug
The file 'config.json' does not exist or contains invalid arguments! Exiting...
alex@b52:~/teslams$ cd examples/
alex@b52:~/teslams/examples$ ./examplestream.js --debug
Calling Streaming API, expect to wait up to 2 minutes for full response...
undefined
alex@b52:~/teslams/examples$
The stream.js does load it correctly, even if called from a different directory.

stream.js keeps giving me 401's.

Thanks for your help.

**Comment by hjespers** [comment]
Ah now I see. The problem is with examplestream.js not with streaming.js. Thats a very old example and it's reading the config.json locally and not using the newer config module. I will update it and test it.

**Comment by hjespers** [comment]
Should be fixes now. examplestream.js now loads credentials from ~/.teslams.config.json just like all the other examples
